import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import NavBar from "./components/NavBar";
import AuthProvider from "./utils/SessionProvider";
import { getServerSession } from "next-auth";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';
import QueryProvider from "./utils/QueryProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session=await getServerSession();
  const user=session?.user
  return (
    <html className="h-full" lang="en">
      <AuthProvider>
        <QueryProvider>
        <body className={cn("relative h-full font-sans antialiased", inter.className)}>
        <ToastContainer
          position='top-center'
          autoClose={3500}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          pauseOnFocusLoss
          pauseOnHover={false}
          theme='light' 
        />
          <main className="relative  flex flex-col min-h-screen">
            <NavBar user={user||null} />
            <div className="flex-grow flex-1">{children}</div>
          </main>
        </body>
      </QueryProvider>
      </AuthProvider>
    </html>
  );
}
