import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import { getServerSession } from "next-auth";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import NavBar from "../components/NavBar";
import { authOptions } from "@/lib/auth";
import User from "@/lib/database/models/UserModel";
import { redirect } from "next/navigation";
import connect from "@/lib/database/connect";
import React from "react";
const inter = Inter({ subsets: ["latin"] });

//todos
/* 
Dashboard for Seller

Overview of sales and revenue
List of products with edit and delete options
Orders management (view orders, update order status)
Sales analytics (charts and graphs)
Product inventory management
Product Form

Step 1: Basic Details
Product name
Price
Description
Stock
Brand
Subcategory
Category
Step 2: Images
Upload multiple images
Preview uploaded images
Save image URLs to database
Step 3: Additional Information
Creator (automatically set from user session)
Attributes and variations (size, color, etc.)
Categories

Define categories for products
Gaming devices
Consoles
Computers
Manage categories (add, edit, delete)
Admin Dashboard

Manage pending products
Approve or reject new products
Orders management
View all orders
Update order status
User management
View and manage users
Assign roles (admin, seller, buyer)

Implement NextAuth for authentication
Role-based access control
Password reset functionality
Product Listing and Search

List products by category
Implement search functionality
Filter products by price, category, and brand
Sort products (by price, popularity, etc.)
Product Details Page

Display product information (name, description, price, images, etc.)
Show product reviews and ratings
Add to cart functionality
Cart and Checkout

Cart management (add, update, remove products)
Checkout process
Shipping information
Payment integration (Stripe, PayPal, etc.)
Order confirmation page
User Profile and Order History

User profile management
Update personal information
Change password
View order history
Track order status
View order details
Review and Rating System

Allow users to leave reviews and ratings for products
Display average rating on product details page
Manage reviews (admin can delete inappropriate reviews)
Notifications and Alerts

Notify users of order status updates
Notify sellers of new orders
Admin notifications for pending product approvals
Responsive Design

*/
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  const user = session?.user;
  await connect();
  const userInfo = await User.findOne({ email: user?.email });
  if (userInfo?.isAdmin) redirect("/admin");
  return (
    <main className="relative  flex flex-col min-h-screen">
      <NavBar user={userInfo || null} />
      <div className="flex-grow flex-1"> {React.cloneElement(children as React.ReactElement, { userInfo })}</div>
    </main>
  );
}
